### ISSUE TITLE
Is real-time transcription available for C#?

### ISSUE THREAD

**Issue by op1031** [AssemblyAI/assemblyai-semantic-kernel#7]
Hi all,
I don't see examples of real-time transcription for this SDK as I see for the SDK for other languages such as Python and Java. So I am wondering if the real-time transcription is available for C#?
Also, Is semantic-kernel the only SDK for C#? 
Thanks!

**Comment by Swimburger** [comment]
Unfortunately, the Semantic Kernel integration is currently the only C# / .NET library we have, but we are actively working on a C# SDK. I don't think it makes sense to put real-time transcription in the SK integration as there's not good extension point from SK to do so.

We're targeting to release the C# SDK as beta in February, and in GA shortly after.
The SDK will include real-time transcription, which you could then use with Semantic Kernel or on its own.

I suggest you watch [the C# SDK repo](https://github.com/AssemblyAI/assemblyai-csharp-sdk), specifically the releases, so you get notified when we have our first release.
<img width="441" alt="Screenshot 2024-01-25 at 2 27 59 PM" src="https://github.com/AssemblyAI/assemblyai-semantic-kernel/assets/3382717/5e3af901-26f6-4910-bd86-31e4f07deab1">
